# .slather.yml

# coverage_service: coveralls
xcodeproj: --scheme SwiftTopStars SwiftTopStars/SwiftTopStars.xcodeproj

# slather coverage -s --scheme SwiftTopStars SwiftTopStars/SwiftTopStars.xcodeproj
