# .slather.yml

coverage_service: coveralls
xcodeproj: SwiftTopStars/SwiftTopStars.xcodeproj
scheme: SwiftTopStars 

# slather coverage -s --scheme SwiftTopStars SwiftTopStars/SwiftTopStars.xcodeproj
