

osx_image: xcode10.3
language: swift
script: 
    - xcodebuild -project SwiftTopStars.xcodeproj -scheme 'SwiftTopStars' -sdk iphonesimulator | xcpretty -c
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X    
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
 - cd SwiftTopStars
 - gem install slather
 - bundle install --without=documentation --path ../travis_bundle_dir
after_success: 
 - slather
 - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
