osx_image: xcode10.1
language: swift
script: 
    - cd SwiftTopStars
    - xcodebuild -project SwiftTopStars.xcodeproj -scheme 'SwiftTopStarsTests' clean archive -configuration release -sdk iphoneos -archivePath SwiftTopStars.xcarchive | xcpretty -c
before_install: 
  - rvm use $RVM_RUBY_VERSION
  - if [[ $RVM_RUBY_VERSION == 'system' ]]; then sudo gem install bundler --no-ri --no-rdoc; else gem install bundler --no-ri --no-rdoc; fi

install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather
