osx_image: xcode10.1
language: swift
script: 
    - cd SwiftTopStars
    - xcodebuild -project SwiftTopStars.xcodeproj -scheme 'SwiftTopStars' clean archive -configuration release -sdk iphoneos -archivePath SwiftTopStars.xcarchive | xcpretty -c
before_install: 
  - rvm use $RVM_RUBY_VERSION

install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather
