

osx_image: xcode10.2
language: swift
xcode_scheme: 'SwiftTopStars'
xcode_project: 'SwiftTopStars/SwiftTopStars.xcodeproj'
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

script: 
# - xcodebuild -project project -scheme scheme -sdk iphonesimulator | xcpretty -c   
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
# - gem install slather
 - bundle install --without=documentation --path ../travis_bundle_dir
after_success: 
 - cd ..
 - slather
 - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
