osx_image: xcode10.3
script: 
    - cd SwiftTopStars
    - xcodebuild -project SwiftTopStars.xcodeproj -scheme 'SwiftTopStars' -sdk iphonesimulator -allowProvisioningUpdates | xcpretty -c
before_install:  rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: 
- slather coverage -s --scheme SwiftTopStars SwiftTopStars/SwiftTopStars.xcodeproj
- bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
