osx_image: xcode10.3
language: swift
script: 
    # - xcodebuild -project SwiftTopStars.xcodeproj -scheme 'SwiftTopStars' -sdk iphonesimulator -allowProvisioningUpdates | xcpretty -c
    - fastlane scan -s SwiftTopStars --sdk iphonesimulator "iPhone X" --clean --code_coverage --verbose 

before_install: 
  - rvm use $RVM_RUBY_VERSION
  - gem install fastlane -NV
  - cd SwiftTopStars
after_success: 
- cd $TRAVIS_BUILD_DIR
- bash <(curl -s https://codecov.io/bash)
   
