

osx_image: xcode10.3
language: swift
build_dir: "build"
script: 
    - cd SwiftTopStars
    - xcodebuild -project SwiftTopStars.xcodeproj -scheme 'SwiftTopStars' -sdk iphonesimulator -derivedDataPath $build_dir -enableCodeCoverage
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X    
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
 - gem install slather
 - bundle install --without=documentation --path ../travis_bundle_dir
after_success: 
 - slather coverage -s --scheme SwiftTopStars --build-directory $build_dir
 - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
